### ISSUE TITLE
Schema Hinting/Number of spaces for formatting 

### ISSUE THREAD

**Issue by gamiller0** [eerohele/exalt#1]
Great plugin!  I have been hoping for a long time that someone would make a package that will validate against an xsd schema.  

I have two requests:
1.  Can you make the number of spaces for XML formatting configurable?  I didn't see a way to do that with your current version.
2.  This is a bigger request, but code hinting based on xsd or other schemas would be a great feature. 

Thanks for the package!

**Comment by eerohele** [comment]
> Great plugin! I have been hoping for a long time that someone would make a package that will validate against an xsd schema.

Thanks! Glad to hear you find it useful.

> 1. Can you make the number of spaces for XML formatting configurable? I didn't see a way to do that with your current version.

Exalt is built on top of [lxml](http://lxml.de), which unfortunately doesn't have an option for defining the number of spaces to use for indentation.

It might be possible to come up with some sort of hack for that, but I'm not sure I want to go there. Also, it would almost certainly hinder performance.

> 1. This is a bigger request, but code hinting based on xsd or other schemas would be a great feature. 

It would indeed be great, but there's no existing library that I know of that I could build something like this on and writing one from scratch would be such a massive undertaking that it's not really realistic, I'm afraid.

Sorry I couldn't be of more help on these issues.

**Comment by bmix** [comment]
As for code hinting based on schema: Wouldn't this be something of service: [xmlschema - An XML Schema validator and decoder](https://pypi.python.org/pypi/xmlschema) which is developed here, [at Github](https://github.com/brunato/xmlschema) ?
