### ISSUE TITLE
Auto-Completion based on scheme.

### ISSUE THREAD

**Issue by deathaxe** [eerohele/exalt#10]
Some XML editors provide a context sensitive auto-completion feature, which suggests valid items to add. 

Is something like that possible to include in exalt or is it meant for validation only?

**Comment by eerohele** [comment]
It's probably possible (and a very useful feature which has also been requested before, see #1), but implementing something like that would be a pretty massive undertaking.

Unfortunately, it's not something I can realistically hope to do in my current situation.

**Comment by deathaxe** [comment]
Oh. Didn't see, sorry for duplicate. Thanks.
