### ISSUE TITLE
After fixing errors validator still shows error

### ISSUE THREAD

**Issue by SASkievua** [eerohele/exalt#13]
WTR:
- put error in xml
- save
- validator shows error
- fix error
- save
- error still shown until document reopened

exalt v0.3.3
sublime text 3.0, build 3143

**Comment by eerohele** [comment]
I can't immediately reproduce the issue.

Are you able to share the XML document you're using, or a snippet from it?

**Comment by eerohele** [comment]
Hmm, in fact, it looks like it occurs when editing an XML document without a DTD or other schema declaration.

Thanks for reporting, I'll look into it.

**Comment by eerohele** [comment]
All right, I have a fix that I think should work, but I'll need to run some tests first. I'll try to cut a new release pretty soon.

**Comment by eerohele** [comment]
I've released v0.3.4, which should fix this issue. It'll take a while to appear on Package Control, but it should be there tomorrow at the latest.

If you can, can you please confirm that the issue is resolved? If not, I'll reopen the issue.

**Comment by infotexture** [comment]
👍 v0.3.4 from Package Control seems to resolve the issue. 

I was able to reproduce the issue before upgrading, but with 0.3.4 the error disappears as soon as the invalid XML is corrected.

**Comment by SASkievua** [comment]
yes, 0.3.4 fixed the issue!
thank you for quick fix! 
and for the great plugin you done!

**Comment by eerohele** [comment]
Glad to hear it, and thanks to you both for checking back!

**Comment by ArturoRR97** [comment]
Im using v0.3.4 and when I modify and save the schema, to validate the xml with the new changes on the schema I need to restart sublime text . Once I close and reopen sublime text the validetor works fine.

**Comment by eerohele** [comment]
@ArturoRR97: Does [this comment](https://github.com/eerohele/exalt/issues/8#issuecomment-290635067) help with that issue?

**Comment by ArturoRR97** [comment]
Thanks for the fast reply ,but what I meant was that the issue remains, it is not enough to close and open the document you need to close and open sublime text each time you made changes to your schema.

**Comment by ArturoRR97** [comment]
Thanks for the fast replay, but what I meant was that the problem remains. It is not enough to close and open the files, instead is necessary to close and open sublime text each time you make changes to your schema.
This are the files I am using, when I change the restriction I need to close sublime to properly validate the xml with the new restriction.

<img width="719" alt="xml" src="https://user-images.githubusercontent.com/23180290/39505306-f72106ae-4d96-11e8-9b35-079b13488a60.png">

<img width="699" alt="xsd" src="https://user-images.githubusercontent.com/23180290/39505309-fc5ab25a-4d96-11e8-81e0-1dcdaa32fa59.png">

**Comment by eerohele** [comment]
What I meant was, running the "Exalt: Clear Parser Cache" command via the Sublime Text command palette should make the schema changes take effect without you having to restart Sublime Text. Did you try that?

**Comment by ArturoRR97** [comment]
Many thanks that solve my problem. Sorry for the annoyance.

**Comment by eerohele** [comment]
No annoyance — that information really should be in the README.
