### ISSUE TITLE
some info about catalogs

### ISSUE THREAD

**Issue by ktrls** [eerohele/exalt#18]
Hi, I would validate some xml comparing with my xsd.

Have I use the catalog? How coudl I configure it on Windows 10?

Thanks a lot

**Comment by eerohele** [comment]
I don't have access to a Windows machine at the moment, but maybe you can take a look at the comments at https://github.com/eerohele/exalt/issues/17 for some pointers.

**Comment by eerohele** [comment]
Did you get it to work? I'm assuming so since I didn't hear back, so I'll close this issue. We can reopen it if you experience any further issues.
