### ISSUE TITLE
Canonical xml using Exalt

### ISSUE THREAD

**Issue by cksachdev** [eerohele/exalt#2]
Is it possible to Canonicalize xml using Exalt? I have seen that lxml is a dependency. I can't find any option to canonicalize xml.

**Comment by eerohele** [comment]
Not at the moment. I can look into it, though.

**Comment by cksachdev** [comment]
@eerohele Thanks, looking forward to it. In the meantime, do you know any such tools which can help me canonicalize the xml in osx.

**Comment by eerohele** [comment]
Something like this should work:

``` bash
$ brew install libxml2
$ xmllint --c14n11 myfile.xml
```

Provided that you have [Homebrew](http://brew.sh) installed.

**Comment by eerohele** [comment]
I've released version 0.3.0, which adds support for canonicalizing XML.

It might take a while for it to appear in Package Control, but when it does, can you please give it a go and let me know whether it works for you?

You can canonicalize a well-formed XML document by selecting "Exalt: Canonicalize Document" from the Sublime Text command palette.

**Comment by cksachdev** [comment]
Thanks, It works for me, there is an issue that it removes the CDATA. Here is a test xml

``` xml
<?xml version="1.0"?>
<theme>
  <controller type="data" name="dictionary" id="dictionary" ><![CDATA[{}]]></controller>
</theme>
```

After canonical run

``` xml
<theme>
  <controller id="dictionary" name="dictionary" type="data">{}</controller>
</theme>
```

Please check why CDATA is removed, it should just arrange the properties in sorted order and should preserve the content as it is.

**Comment by eerohele** [comment]
It seems that [the W3C specification for canonical XML](https://www.w3.org/TR/xml-c14n#Terminology) dictates that "CDATA sections are replaced with their character content", so the current behavior is correct.

Anyway, it's [libxml2](http://www.xmlsoft.org/) that does the actual canonicalization, so there's little I can do to modify the behavior.
