### ISSUE TITLE
Validation error disappears from screen

### ISSUE THREAD

**Issue by stodge** [eerohele/exalt#20]
If I select a line in an XML file that failed to validate against the XSD file, the error appears in the status bar at the bottom of the application. However, it disappears after a few seconds so I can no longer read the error. Is this expected? Are the errors logged anywhere else? Thanks

**Comment by eerohele** [comment]
Not expected. Are you able to attach samples of the XML and XSD files you're working with to this issue?

**Comment by eerohele** [comment]
This should be fixed in v0.3.7.

It'll a take a while to land in Package Control, but if you have the time, could you give it a go and let me know whether it fixes the issue for you?

**Comment by stodge** [comment]
Thanks, I'll try to install it soon.

**Comment by eerohele** [comment]
I'll close this, but if the issue isn't fixed for you, please let me know and I'll take another look.
