### ISSUE TITLE
add instruction to restart sublime after install

### ISSUE THREAD

**Issue by drevicko** [eerohele/exalt#7]
at least for me (osX, ST3) exalt did not appear immediately in the cmd-shit-P menu, only after I restarted sublime.

**Comment by eerohele** [comment]
Thanks for the report! You're correct, you do need to restart Sublime Text for Exalt to work.

I've [updated the README](https://github.com/eerohele/exalt/blob/4c9c05c9950cdcdc582934bfa7f38de66130e6c6/README.md#installing) accordingly.
